feat lilypad serve with ipfs fix
Lilypad-Tech/lilypad pull request #398
Opened 2024-10-03 22:49 UTC by arsen3d

### Summary
This release includes functionality replicates 'lilypad run' as rest end point

To test:
```
go run . --network dev serve
```
Open postman
POST:
```
http://127.0.0.1:9876/run/job
```
BODY:
```
{
    "module": "github.com/noryev/module-sdxl-ipfs:ae17e969cadab1c53d7cabab1927bb403f02fd2a",
    "input": {
        "name": "prompt",
        "value": "bunny and fox"
    }
}
```
RESULT:
```
{
    "cid": "QmVc3b2gemJP4NEpdyWQx5dL1EkuKFVbDocGedy43KSpW4",
    "dataid": "QmfHcU8YqrhA2RbdwB6zNY8FSFnM43pvpC7NrgBgjCXsCV"
}
```
Open New Postman Tab
GET:
```
http://127.0.0.1:9876/files/QmfHcU8YqrhA2RbdwB6zNY8FSFnM43pvpC7NrgBgjCXsCV/outputs/output.png
```

EXAMPLE:
![image](https://github.com/user-attachments/assets/24839af0-b255-4f3e-8525-db47a8e4713a)

![image](https://github.com/user-attachments/assets/3fccf22f-4766-4065-88d7-2c9b7929a808)

2024-10-04 17:46 UTC, bgins requested changes
@arsen3d @noryev could you write up an PRD explaining the approach in this PR? Seeing a few different elements at play here, and it would help to understand the design for these features.

2024-10-04 17:55 UTC, bgins commented
Seems like the unit and integration tests aren't running here. Was there a change to them?

2024-10-04 19:11 UTC, kelindi commented
Is the end user supposed to run this and use it as a backend of sorts to interact with lilypad? If so it might make sense to have this be part of a standalone repo

2024-10-10 16:13 UTC, bgins commented
Thanks for this proof-of-concept @arsen3d! We used some ideas from it implementing #400.

The `serve` command is an intriguing idea. Would love to see a write up for it. As @kelindi mentioned, it may be something we would want to implement as a standalone repo.

2024-10-10 16:13 UTC, closed without merging